//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Erags.rc
//
#define IDR_CNTR_INPLACE                6
#define IDM_REGKEYS                     16
#define IDD_ABOUTBOX                    100
#define IDD_ERAFORM                     101
#define IDD_FORM_BIRTH                  102
#define IDD_FORM_FATHER                 103
#define IDD_FORM_MARRIAGE               104
#define IDD_FORM_DIVORCE                105
#define IDD_FORM_CHANGE                 106
#define IDD_FORM_DEATH                  107
#define CG_IDD_PROGRESS                 108
#define CG_IDS_PROGRESS_CAPTION         109
#define ID_REGISTATION                  110
#define IDS_PANE_ICON                   112
#define IDS_PANE_LABEL                  113
#define IDR_TREEFILECTRL_POPUP          114
#define IDP_FAILED_OPEN_DATABASE        126
#define IDR_MAINFRAME                   128
#define IDR_ERAGSTYPE                   129
#define IDC_FOLDER_TREE                 129
#define IDI_ERAGS_GRP                   130
#define IDC_DROP_COPY_ROOT              130
#define IDB_MALE                        131
#define IDC_DROP_MOVE_ABOVE             131
#define IDB_FEMALE                      132
#define IDC_DROP_COPY_ABOVE             132
#define IDB_NEW                         133
#define IDR_TREEFILECTRL_NO_DROPCOPY    133
#define IDB_FIRST                       134
#define IDR_TREEFILECTRL_DROPCOPY       134
#define IDB_PREV                        135
#define IDB_NEXT                        136
#define IDB_LAST                        137
#define IDR_FILEDROPDOWN                138
#define IDB_IMLIST                      138
#define IDD_MILITARY                    139
#define IDB_MLT                         140
#define IDC_NODROP                      140
#define IDB_MLT_FOCUS                   141
#define IDB_MLT_DOWN                    142
#define IDC_DROP_MOVE_ROOT              142
#define IDD_PASSPORTS                   143
#define IDD_SVIDDIV                     144
#define IDC_DROP_COPY_SON               144
#define IDD_DIVORCE_18                  145
#define IDI_UKRAINE                     146
#define IDC_DROP_MOVE_SON               146
#define IDB_UKRAINE                     147
#define IDD_DIVORCE_23                  148
#define IDD_BANKS                       149
#define IDI_ATTENTION                   150
#define IDB_NOFOCUS                     151
#define IDD_FILENEW                     152
#define IDB_NODOWN                      153
#define IDD_ABCFORM_MARRIAGE            154
#define IDD_SETTINGS                    155
#define IDB_NO                          156
#define IDD_SETTINGS_COMMON             157
#define IDD_SETTINGS_BIRTH              158
#define IDD_SETTINGS_MARRIAGE           159
#define IDD_SETTINGS_DIVORCE            160
#define IDD_SETTINGS_CHANGE             161
#define IDD_SETTINGS_DEATH              162
#define IDD_SETTINGS_APPEARANCE         163
#define IDD_SETTINGS_ARCHIVE            164
#define IDB_YESFOCUS                    165
#define IDD_ABCFORM_DEATH               166
#define IDD_DBNAMES                     167
#define IDB_YESDOWN                     168
#define IDB_GIRL                        169
#define IDB_YES                         170
#define IDI_CHANGE                      171
#define IDI_DEATH                       172
#define IDI_DIVORCE                     173
#define IDI_FATHER                      174
#define IDI_BIRHT                       175
#define IDR_WAVE1                       176
#define IDIL_ABCHEADER                  177
#define IDD_DEFPLACE                    178
#define IDR_WAVE2                       179
#define IDB_BIRTH                       180
#define IDB_MARRIAGE                    181
#define IDB_CHANGE                      182
#define IDB_DEATH                       183
#define IDB_DIVORCE                     184
#define IDD_GEOGRAPHY                   185
#define IDD_DLG43                       186
#define IDD_DATAGRID                    187
#define IDI_COUNTRY                     188
#define IDD_TABLEVIEW                   189
#define IDIL_GEOTREE                    190
#define IDB_PLUS_FOCUS                  191
#define IDB_PLUS_DOWN                   192
#define IDB_PLUS                        193
#define IDM_GEOMENU                     194
#define IDR_DATAGRID                    195
#define IDD_ADDGEODLG                   197
#define IDB_YESDISABLED                 199
#define IDD_EXTBIRTH                    201
#define IDR_PRINT                       202
#define IDR_REQ                         203
#define IDR_REPORTFRAME                 204
#define IDD_FORM_PREVIEW                205
#define IDR_RFIND                       205
#define IDD_DBGRID                      206
#define IDB_COLLATE1                    207
#define IDI_CLOSE_APP                   208
#define IDI_INFO                        209
#define IDI_MEDICS                      210
#define IDD_ADD_REASON                  211
#define IDI_NEWNAMES                    212
#define IDR_ABC                         213
#define IDD_INFO                        215
#define IDB_LEDS                        216
#define IDD_THATS_ALL                   217
#define IDB_FOUNDLIST                   217
#define IDR_REPORFRAME                  224
#define IDD_CHANGE_27                   225
#define IDD_CHANGE_29                   226
#define IDD_ABC                         227
#define IDI_WORD8                       228
#define IDI_WORD9                       229
#define IDR_WORD                        230
#define IDD_TEMPLATES                   232
#define IDB_ACTIONS                     233
#define IDB_ACTIONS1                    234
#define IDB_ACTIONS2                    235
#define IDB_ACTIONS3                    236
#define IDB_ACTIONS4                    237
#define IDB_ACTIONS5                    238
#define IDB_ACTIONS6                    239
#define IDB_ACTIONS7                    240
#define IDB_ACTIONS8                    241
#define IDD_ERRDATEREG                  242
#define IDD_ABC_DEATH                   248
#define IDD_ABC_BIRTH                   249
#define IDD_ABC_MARRIAGE                250
#define IDD_ABC_DIVORCE                 251
#define IDD_ABC_CHANGE                  252
#define IDB_MAN256                      253
#define IDB_WOMAN256                    254
#define IDB_BIRTH256                    256
#define IDB_FIANCE256                   257
#define IDB_FIANCEE256                  258
#define IDB_DEATH256                    259
#define IDIL_BROWSER_COLDTOOLBAR        261
#define IDIL_BROWSER_HOTTOOLBAR         262
#define IDD_FIND                        263
#define IDR_SEARCH                      264
#define IDB_YES256                      268
#define IDB_YESFOCUS256                 269
#define IDB_NO256                       270
#define IDB_NOFOCUS256                  271
#define IDB_NODOWN256                   273
#define IDB_FILE_OPEN                   274
#define IDB_FILE_OPEN_OUT               276
#define IDTB_MAIN_TOOLBAR               277
#define IDB_BTN_BIRTH                   280
#define IDB_BTN_BIRTH_OUT               281
#define IDB_BTN_MARRIAGE                282
#define IDB_BTN_MARRIAGE_OUT            283
#define IDB_BTN_DIVORCE                 284
#define IDB_BTN_DIVORCE_OUT             286
#define IDB_BTN_BEATH                   287
#define IDB_BTN_DEATH_OUT               289
#define IDB_BTN_DEATH                   291
#define IDB_BTN_CHANGE                  292
#define IDB_BTN_CHANGE_OUT              293
#define IDB_BTN_ABC                     294
#define IDB_BTN_ABC_OUT                 295
#define IDB_BTN_EXTNOTES                296
#define IDB_BTN_EXTNOTES_OUT            297
#define IDB_BTN_GEOGRAPHY               298
#define IDB_BTN_GEOGRAPHY_OUT           299
#define IDB_BTN_RED_CROSS               300
#define IDB_BTN_RED_CROSS_OUT           301
#define IDB_BTN_CITY_HALL               302
#define IDB_BTN_CITY_HALL_OUT           303
#define IDB_BTN_UKRAINE                 304
#define IDB_BTN_UKRAINE_OUT             306
#define IDB_BTN_UAH                     307
#define IDB_BTN_UAH_OUT                 308
#define IDB_BTN_FIRST                   309
#define IDB_BTN_FIRST_OUT               310
#define IDB_BTN_PREV                    311
#define IDB_BTN_PREV_OUT                313
#define IDB_BTN_NEXT                    314
#define IDB_BTN_NEXT_OUT                315
#define IDB_BTN_LAST                    316
#define IDB_BTN_LAST_OUT                317
#define IDB_BTN_RECORD_NEW              318
#define IDB_BTN_RECORD_NEW_OUT          319
#define IDB_BTN_RECORD_DELETE           320
#define IDB_BTN_RECORD_DELETE_OUT       321
#define IDB_BTN_FINDIN                  322
#define IDB_BTN_FINDOUT                 323
#define IDB_BTN_FINDOUT_OUT             324
#define IDB_BTN_PRINT                   325
#define IDB_BTN_PRINT_OUT               326
#define IDB_BTN_WORD                    327
#define IDB_BTN_WORD_OUT                328
#define IDB_BTN_HELP                    329
#define IDB_BTN_HELP_OUT                330
#define IDB_BTN_RECENT                  331
#define IDB_BTN_TEMPLATES               332
#define IDB_BTN_TEMPLATES_OUT           333
#define IDR_NEWMENU256                  337
#define IDB_BTN_FILE_NEW                338
#define IDR_PRINTMENU                   339
#define IDR_PRINT_DIVORCE               340
#define IDB_BOY                         341
#define IDTB_ABC_TOOLBAR                341
#define IDB_BTN_LEFT                    342
#define IDB_BTN_UP                      343
#define IDB_BTN_RIGHT                   344
#define IDB_BTN_DOWN                    345
#define IDIL_ABCSEX                     346
#define IDB_HDRUP                       349
#define IDB_HDRDOWN                     350
#define IDB_BTN_SETCOLORS               355
#define IDB_BTN_FOLDER_TREE             356
#define IDB_MAINTOOLBAR                 357
#define IDI_FOLDERTREE                  358
#define IDI_COMMON_SETTINGS             359
#define IDI_SETCOLORS                   360
#define IDI_SETBIRTH                    361
#define IDI_SETMARRIAGE                 362
#define IDI_SETDIVORCE                  363
#define IDI_SETCHANGE                   364
#define IDI_SETDEATH                    365
#define IDD_FILE_NEW                    366
#define IDR_TREEFILECTRL_NO_DROPMOVE    367
#define IDTB_RFIND                      369
#define IDB_BTN_SAVE_AS                 370
#define IDB_BTN_EQU                     371
#define IDB_BTN_PARTIAL                 372
#define IDB_BTN_OPEN_RECORD             373
#define IDB_BTN_FOLDER_TREE1            375
#define IDB_CALENDAR                    377
#define IDD_SVIDADOPTION                378
#define IDI_CROSSW                      379
#define IDI_CROSSM                      381
#define IDI_SIGNMALE                    382
#define IDI_SIGNFEMALE                  383
#define IDI_YES                         384
#define IDI_NO                          385
#define IDD_RLIST                       386
#define IDIL_RFOLDERS                   387
#define IDD_RLIST_DELETE                388
#define IDD_RLIST_ADD                   389
#define IDI_UP                          390
#define IDD_DBLOAD                      391
#define IDR_POST                        392
#define IDD_ENVELOPE                    393
#define IDM_RLIST                       394
#define IDD_CHECKDATE                   395
#define IDD_OPEN_RECORD                 396
#define IDD_EXPIRED                     398
#define IDC_HAND_CURSOR                 399
#define IDB_TOOLBAR_NORMAL              401
#define IDB_TOOLBAR_HOT                 402
#define IDB_TOOLBAR_DISABLED            403
#define IDD_ELECTION_CHANGES            404
#define IDD_ELECTION_DEATH              406
#define IDR_MANIFEST                    409
#define IDR_RTF1                        410
#define IDR_RTF2                        411
#define IDR_RTF3                        412
#define IDD_REGKEYS                     420
#define IDI_WATCH                       421
#define IDD_DOYOUZIP                    422
#define IDD_UNZIPDLG                    423
#define IDIL_ZIPFILES                   425
#define IDIL_ZIPSORT                    427
#define IDD_CANT_OPEN                   428
#define IDD_ZIP_OFFER                   429
#define IDD_ZIPDB                       431
#define IDRTF_EMPTY                     433
#define IDIL_ZIP                        434
#define IDIL_RADIOXP                    435
#define IDIL_CHECKBOXXP                 436
#define IDR_SYSMENU                     438
#define IDR_NAVIGATORS                  445
#define IDD_BIRTH_11                    446
#define IDD_BIRTH_09                    447
#define IDTB_TOOLBARS                   448
#define IDIL_MESSAGES                   449
#define IDD_NAMELIST                    451
#define IDD_NAMES                       451
#define IDR_DBGRID                      452
#define IDI_RECORD_NEW                  453
#define IDI_RECORD_DELETE               454
#define IDI_RECORD_EDIT                 455
#define IDD_BIRTH_NAMES                 456
#define IDR_TXT1                        457
#define IDD_RLISTFORM                   458
#define IDB_BTN_SAVE_AS_OUT             460
#define IDI_SETZIP                      461
#define IDD_COPY2EXCEL                  464
#define IDD_GEOFORM                     465
#define IDB_BTN_LAWS                    468
#define IDB_BTN_LAWS_OUT                469
#define IDR_BROWSER                     470
#define IDTB_BROWSER                    472
#define IDIL_FONT                       474
#define IDD_BLANKS                      475
#define IDD_ANTENUPTIAL                 479
#define IDD_SETTINGS_OFFICE             480
#define IDI_SETOFFICE                   481
#define IDB_BTN_SWRITER                 482
#define IDB_BTN_SWRITER_OUT             483
#define IDD_LOGIN                       485
#define IDI_KEYS                        486
#define IDD_ADD_USER                    487
#define IDI_USERS                       488
#define IDD_SETTINGS_USERS              490
#define IDB_ACTA2                       493
#define IDB_ACTA1                       494
#define IDB_ACTB                        495
#define IDD_SETTINGS_STAMPS             496
#define IDI_STAMP                       497
#define IDB_CITYTYPE2                   499
#define IDB_CITYTYPE1                   500
#define IDIL_RFOLDERS_TC                501
#define ID_PRINT_FIRST                  1000
#define ID_PRINT_BIRTH_ACT              1001
#define ID_PRINT_BIRTH_CERTIFICATE      1002
#define CG_IDC_PROGDLG_PROGRESS         1003
#define ID_PRINT_ADOPTION_CERTIFICATE   1003
#define CG_IDC_PROGDLG_PERCENT          1004
#define ID_PRINT_BIRTH_8                1004
#define ID_PRINT_BIRTH_9                1005
#define CG_IDC_PROGDLG_STATUS           1005
#define ID_PRINT_BIRTH_AFFILIATION_09   1006
#define IDC_DONTSHOW                    1007
#define ID_PRINT_BIRTH_AFFILIATION_11   1007
#define IDC_MSGTEXT                     1008
#define ID_PRINT_BIRTH_41               1008
#define ID_PRINT_BIRTH_42               1009
#define ID_PRINT_BIRTH_ABC              1010
#define ID_PRINT_BIRTH_FORTAX           1011
#define ID_PRINT_BIRTH_BLANKS           1020
#define ID_PRINT_BIRTH_01_2_3           1021
#define ID_PRINT_BIRTH_02_2_15          1022
#define ID_PRINT_BIRTH_04_2_16          1023
#define ID_PRINT_BIRTH_05_2_17          1024
#define ID_PRINT_BIRTH_06_2_19          1026
#define ID_PRINT_BIRTH_07_2_20          1027
#define ID_PRINT_BIRTH_08_2_29          1028
#define ID_PRINT_BIRTH_09_2_30          1029
#define ID_PRINT_BIRTH_31_7_1           1030
#define ID_PRINT_BIRTH_35_7_1           1031
#define ID_PRINT_BIRTH_39_7_8           1032
#define ID_PRINT_BIRTH_40_7_8           1033
#define ID_PRINT_BIRTH_41_7_8           1034
#define ID_PRINT_BIRTH_42_7_8           1035
#define ID_PRINT_BIRTH_49_7_8           1036
#define ID_PRINT_BIRTH_50_7_8           1037
#define ID_PRINT_BIRTH_51_7_8           1038
#define ID_PRINT_BIRTH_54_7_8           1039
#define ID_PRINT_MARRIAGE_ACT           1101
#define ID_PRINT_MARRIAGE_CERIFICATE    1102
#define ID_PRINT_ANTENUPTIAL            1103
#define ID_PRINT_MARRIAGE_ABC           1104
#define ID_PRINT_MARRIAGE_BLANKS        1120
#define ID_PRINT_MARRIAGE_14_4_1        1121
#define ID_PRINT_MARRIAGE_15_4_28       1122
#define ID_PRINT_MARRIAGE_33_7_1        1123
#define ID_PRINT_MARRIAGE_37_7_7        1124
#define ID_PRINT_MARRIAGE_38_7_7        1125
#define ID_PRINT_MARRIAGE_39_7_8        1126
#define ID_PRINT_MARRIAGE_40_7_8        1127
#define ID_PRINT_MARRIAGE_44_7_8        1128
#define ID_PRINT_MARRIAGE_45_7_8        1129
#define ID_PRINT_MARRIAGE_46_7_8        1130
#define ID_PRINT_MARRIAGE_51_7_8        1131
#define ID_PRINT_MARRIAGE_52_7_8        1132
#define ID_PRINT_MARRIAGE_53_7_8        1133
#define ID_PRINT_MARRIAGE_54_7_8        1134
#define ID_PRINT_DIVORCE_ACT            1201
#define ID_PRINT_DIVORCE_CERIFICATE1    1202
#define ID_PRINT_DIVORCE_CERIFICATE2    1203
#define ID_PRINT_DIVORCE_16             1204
#define ID_PRINT_DIVORCE_18_1           1205
#define ID_PRINT_DIVORCE_18_2           1206
#define ID_PRINT_DIVORCE_21             1207
#define ID_PRINT_DIVORCE_22             1208
#define ID_PRINT_DIVORCE_23             1209
#define ID_PRINT_DIVORCE_ABC            1210
#define ID_PRINT_DIVORCE_BLANKS         1220
#define ID_PRINT_DIVORCE_15_5_25        1221
#define ID_PRINT_DIVORCE_16_5_2         1222
#define ID_PRINT_DIVORCE_17_5_4         1223
#define ID_PRINT_DIVORCE_19_5_12        1224
#define ID_PRINT_DIVORCE_20_5_19        1225
#define ID_PRINT_DIVORCE_21_5_19        1226
#define ID_PRINT_DIVORCE_22_5_20        1227
#define ID_PRINT_DIVORCE_23_5_22        1228
#define ID_PRINT_DIVORCE_24_5_22        1229
#define ID_PRINT_DIVORCE_34_7_1         1230
#define ID_PRINT_DIVORCE_39_7_8         1231
#define ID_PRINT_DIVORCE_40_7_8         1232
#define ID_PRINT_DIVORCE_47_7_8         1233
#define ID_PRINT_DIVORCE_51_7_8         1234
#define ID_PRINT_DIVORCE_52_7_8         1235
#define ID_PRINT_DIVORCE_53_7_8         1236
#define ID_PRINT_DIVORCE_54_7_8         1237
#define ID_PRINT_CHANGE_ACT             1301
#define ID_PRINT_CHANGE_CERIFICATE      1302
#define ID_PRINT_CHANGE_27              1303
#define ID_PRINT_CHANGE_28              1304
#define ID_PRINT_CHANGE_29              1305
#define ID_PRINT_CHANGE_30              1306
#define ID_PRINT_CHANGE_ABC             1307
#define ID_PRINT_CHANGE_ELECTIONS       1308
#define ID_PRINT_CHANGE_BLANKS          1320
#define ID_PRINT_CHANGE_15_6_13         1321
#define ID_PRINT_CHANGE_25_6_1          1322
#define ID_PRINT_CHANGE_26_6_9          1323
#define ID_PRINT_CHANGE_27_6_10         1324
#define ID_PRINT_CHANGE_28_6_12         1325
#define ID_PRINT_CHANGE_29_6_13         1326
#define ID_PRINT_CHANGE_30_6_13         1327
#define ID_PRINT_CHANGE_36_7_1          1328
#define ID_PRINT_CHANGE_39_7_8          1329
#define ID_PRINT_CHANGE_40_7_8          1330
#define ID_PRINT_CHANGE_51_7_8          1331
#define ID_PRINT_CHANGE_54_7_8          1332
#define ID_PRINT_DEATH_ACT              1401
#define ID_PRINT_DEATH_CERIFICATE       1402
#define ID_PRINT_DEATH_DOV              1403
#define ID_PRINT_DEATH_DOV43            1404
#define ID_PRINT_DEATH_FORTAX           1405
#define ID_PRINT_DEATH_FORTAX_13        1406
#define ID_PRINT_DEATH_FORSOCPROT       1407
#define ID_PRINT_DEATH_CHILDREN         1408
#define ID_PRINT_DEATH_PASSPORTS        1409
#define ID_PRINT_DEATH_ABC              1410
#define ID_PRINT_DEATH_ELECTIONS        1411
#define ID_PRINT_DEATH_BLANKS           1420
#define ID_PRINT_DEATH_10_3_11          1421
#define ID_PRINT_DEATH_11_3_12          1422
#define ID_PRINT_DEATH_12_3_13          1423
#define ID_PRINT_DEATH_13_3_13          1424
#define ID_PRINT_DEATH_32_7_1           1425
#define ID_PRINT_DEATH_39_7_8           1426
#define ID_PRINT_DEATH_40_7_8           1427
#define ID_PRINT_DEATH_43_7_8           1428
#define ID_PRINT_DEATH_54_7_8           1429
#define ID_PRINT_BLANK_REGISTER         1500
#define ID_PRINT_ENVELOPE_A4_UKR        1501
#define ID_PRINT_ENVELOPE_A4_RUS        1502
#define ID_PRINT_ENVELOPE_DL_UKR        1503
#define ID_PRINT_ENVELOPE_DL_RUS        1504
#define ID_PRINT_ENVELOPE_229x114_UKR   1505
#define ID_PRINT_ENVELOPE_229x114_RUS   1506
#define ID_PRINT_ENVELOPE_229x162_UKR   1507
#define ID_PRINT_ENVELOPE_229x162_RUS   1508
#define ID_PRINT_ENVELOPE_162x114_UKR   1509
#define ID_PRINT_ENVELOPE_162x114_RUS   1510
#define ID_PRINT_LAST                   1600
#define IDC_DATEREG                     2003
#define IDC_MARRIAGE_DATE               2004
#define IDC_GROUND                      2005
#define IDC_NUMBER                      2006
#define IDC_SEX                         2007
#define IDC_DATE                        2008
#define IDC_MARRIAGE_NUMBER             2009
#define IDC_BIRTH_PLACE                 2010
#define IDC_MILOFFICE                   2011
#define IDC_MMARRIAGE_NUMBER            2012
#define IDC_SURNAME                     2013
#define IDC_WMARRIAGE_NUMBER            2014
#define IDC_DATEOFBIRTH                 2015
#define IDC_GROUND_NUMBER               2016
#define IDC_NKIDS                       2017
#define IDC_CHANGE                      2018
#define IDC_BYCOUNT                     2019
#define IDC_GROUND_DATE                 2020
#define IDC_MEDICAL_CERTIFICATE_NUMBER  2021
#define IDC_MEDICAL_CERTIFICATE_DATE    2022
#define IDC_SOURCE_NDOC                 2023
#define IDC_SOURCE_DATE                 2024
#define IDC_FATHER_SURNAME              2025
#define IDC_NAME                        2026
#define IDC_MNEW_SURNAME                2027
#define IDC_ALTNAME                     2027
#define IDC_PATRONYMIC                  2028
#define IDC_CODES                       2028
#define IDC_WNEW_SURNAME                2029
#define IDC_ZIP_CODES                   2029
#define IDC_BIRTH_COUNTRY               2030
#define IDC_DIRECTORY                   2030
#define IDC_CITIZENSHIP                 2031
#define IDC_ALIVE_FLAG                  2032
#define IDC_BIRTH_REGION                2033
#define IDC_REASON_PSEUDO               2034
#define IDC_BIRTH_DISTRICT              2035
#define IDC_MEDICAL_CERT_TYPE           2036
#define IDC_BIRTH_CITY                  2037
#define IDC_MEDICAL_CERT_BY_PSEUDO      2038
#define IDC_COMBO_NEWNAME               2039
#define IDC_MEDICAL_CERTIFICATE_PSEUDUNYM 2040
#define IDC_MEDICAL_CERT_BY             2041
#define IDC_CASE                        2042
#define IDC_COMBO_NEWPATRONYMIC         2043
#define IDC_BC_LABEL                    2044
#define IDC_BR_LABEL                    2045
#define IDC_WHATICON                    2046
#define IDC_BD_LABEL                    2047
#define IDC_TYPE                        2048
#define IDC_BV_LABEL                    2049
#define IDC_PLACETYPE                   2050
#define IDC_MEDICAL_CERTIFICATE_BY      2051
#define IDC_COUNTRY_LABEL               2052
#define IDC_SOURCE_BY                   2053
#define IDC_REGION_LABEL                2054
#define IDC_FATHER_CITIZENSHIP          2055
#define IDC_BOSS                        2056
#define IDC_DISTRICT_LABEL              2057
#define IDC_PIBPO                       2057
#define IDC_BYUMVS                      2058
#define IDC_MOTHER_CITIZENSHIP          2059
#define IDC_POSADA                      2059
#define IDC_BYMIL                       2060
#define IDC_CITY_LABEL                  2061
#define IDC_BYCOURT                     2062
#define IDC_FATHER_NAME                 2063
#define IDC_TOTAX                       2064
#define IDC_COUNTRY                     2065
#define IDC_FATHER_PATRONYMIC           2066
#define IDC_REGION                      2067
#define IDC_MOTHER_SURNAME              2068
#define IDC_DISTRICT                    2069
#define IDC_MOTHER_NAME                 2070
#define IDC_CITY                        2071
#define IDC_MOTHER_PATRONYMIC           2072
#define IDC_RAGS                        2073
#define IDC_CHECK_COUNTRY               2074
#define IDC_OKPO                        2074
#define IDC_PARENT                      2075
#define IDC_CHILD                       2076
#define IDC_FATHER_BIRTH_DATE           2077
#define IDC_TOUMVS                      2078
#define IDC_CHECK_REGION                2079
#define IDC_TOMIL                       2080
#define IDC_MOTHER_BIRTH_DATE           2081
#define IDC_CHECK_DISTRICT              2082
#define IDC_FATHER_HOUSE                2083
#define IDC_CHECK_CITY                  2084
#define IDD_FSTATUS                     2085
#define IDC_FATHER_COUNTRY              2086
#define IDC_FATHER_FLAT                 2087
#define IDC_SOURCE_TYPE                 2088
#define IDC_SOURCE_OF_LABEL             2089
#define IDC_SOURCE_BY_LABEL             2090
#define IDC_MCITIZEN_LABEL              2091
#define IDC_WCITIZEN_LABEL              2092
#define IDC_FATHER_REGION               2093
#define IDC_MOTHER_COUNTRY              2095
#define IDD_NOTECHANGE                  2097
#define IDD_SVID                        2098
#define IDC_FATHER_DISTRICT             2099
#define IDD_DEPENDENCES                 2100
#define IDD_YESNO                       2101
#define IDC_MOTHER_REGION               2102
#define IDC_FATHER_CITY                 2103
#define IDD_BIRTH_08                    2104
#define IDC_FATHER_STREET               2105
#define IDC_MOTHER_DISTRICT             2106
#define IDC_MOTHER_CITY                 2107
#define IDC_MOTHER_STREET               2108
#define IDC_MOTHER_HOUSE                2109
#define IDC_MOTHER_FLAT                 2110
#define IDC_DECLARANT_TYPE              2111
#define IDC_DECLARANT_NAME              2112
#define IDD_LISTDLG                     2113
#define IDC_DECLARANT_ADDRESS           2114
#define IDC_GEOTREE                     2115
#define IDC_DECLARANT_PASSPORT_TYPE     2116
#define IDC_GEOPATH                     2117
#define IDC_DECLARANT_PASSPORT_SERIA    2118
#define IDC_GEOTYPE                     2119
#define IDC_BIRTHACT_NUMBER             2120
#define IDD_NOTEDLG                     2121
#define IDC_DECLARANT_PASSPORT_NUMBER   2122
#define IDD_ABCFORM_BIRTH               2122
#define IDD_SETDEFVAL                   2122
#define IDC_NEWGEO                      2123
#define IDD_ABCFORM_CHANGE              2123
#define IDD_REGISTRATION                2123
#define IDC_DECLARANT_PASSPORT_DATE     2124
#define IDD_ABCFORM_DIVORCE             2124
#define IDC_NEWTYPE                     2125
#define IDC_BIRTHACT_DATE               2126
#define IDC_DECLARANT_PASSPORT_BY       2127
#define IDC_ADD                         2128
#define IDC_LBLNAME                     2129
#define IDC_CERTIFICATE_SERIA           2130
#define IDC_CERTIFICATE_NUMBER          2131
#define IDC_LBLFULLNAME                 2132
#define IDC_NOTICE                      2133
#define IDC_FULLNAME                    2134
#define IDC_GRID                        2135
#define IDC_LBLTYPE                     2136
#define IDC_FULLREGNAME                 2137
#define IDC_LABEL_MOTHER_SURNAME        2138
#define IDC_SHORTNAME                   2138
#define IDR_CONTEXT                     2139
#define IDC_NEWSURNAME                  2140
#define IDC_NEWFATHERDATE               2141
#define IDC_NEWMOTHERDATE               2142
#define IDC_NEWMOTHERSURNAME            2143
#define IDC_MEMO                        2144
#define IDC_LABEL_NEWSURNAME            2145
#define IDC_LABEL_NEWNAME               2146
#define IDC_EXPLORER                    2147
#define IDC_GR10TEXT                    2148
#define IDC_LABEL_NEWPATRONYMIC         2149
#define IDC_LABEL_FATHERDATE            2150
#define IDC_DEATH_DATE                  2151
#define IDC_LABEL_MOTHERDATE            2152
#define IDC_DP_COUNTRY                  2153
#define IDC_LABEL_MOTHERNEWSURNAME      2154
#define IDC_DP_REGION                   2155
#define IDC_DP_DISTRICT                 2156
#define IDC_DP_CITY                     2157
#define IDC_BIRTH_DATE                  2158
#define IDC_BP_COUNTRY                  2159
#define IDC_BP_REGION                   2160
#define IDC_BP_DISTRICT                 2161
#define IDC_BP_CITY                     2162
#define IDC_REASON                      2163
#define IDC_MEDICAL_CERT_NUMBER         2164
#define IDC_MEDICAL_CERT_DATE           2165
#define IDC_RP_ZIPCODE                  2166
#define IDC_RP_COUNTRY                  2167
#define IDC_RP_REGION                   2168
#define IDC_RP_DISTRICT                 2169
#define IDC_RP_CITY                     2170
#define IDC_RP_STREET                   2171
#define IDC_RP_HOUSE                    2172
#define IDC_RP_FLAT                     2173
#define IDC_PASSPORT_TYPE               2174
#define IDC_PASSPORT_SERIA              2175
#define IDC_PASSPORT_NUMBER             2176
#define IDC_PASSPORT_DATE               2177
#define IDC_PASSPORT_BY                 2178
#define IDC_LBL_AGE                     2179
#define IDC_DATELIST                    2181
#define IDC_CHILDLIST                   2182
#define IDC_IN                          2183
#define IDC_PAGE1                       2184
#define IDC_PAGE2                       2185
#define IDC_MONLIST                     2186
#define IDC_REPEAT                      2187
#define IDC_FROM                        2188
#define IDC_STRIKE_OUT                  2188
#define IDC_DATEV                       2189
#define IDC_DATEOUT                     2190
#define IDC_YNMESSAGE                   2190
#define IDC_NDOV                        2190
#define IDC_TILL                        2191
#define IDC_YNQUESTION                  2192
#define IDC_FULLNAME2                   2193
#define IDC_COMBORAGS                   2194
#define IDC_FULLNAME1                   2195
#define IDC_NOTEFLD                     2196
#define IDC_REGPLACE                    2197
#define IDC_DFROM                       2198
#define IDC_OWNER                       2199
#define IDC_DTILL                       2200
#define IDC_NOTEMENU                    2201
#define IDC_MCITIZENSHIP                2202
#define IDC_DBIRTH                      2203
#define IDC_WCITIZENSHIP                2204
#define IDC_MOLD_SURNAME                2205
#define IDC_BPLACE                      2206
#define IDC_WOLD_SURNAME                2207
#define IDC_MOLD_SURNAME2               2208
#define IDC_MNAME                       2209
#define IDC_MPATRONYMIC                 2210
#define IDC_WNAME                       2211
#define IDC_WPATRONYMIC                 2212
#define IDC_ACTLIST                     2213
#define IDC_MNEWSURNAME                 2213
#define IDC_MBIRTH_DATE                 2214
#define IDC_WNEWSURNAME                 2214
#define IDC_WBIRTH_DATE                 2215
#define IDC_SURNAME_DV                  2216
#define IDC_MCHECK_DATE                 2217
#define IDC_MBIRTH_COUNTRY              2218
#define IDC_NAME_DV                     2219
#define IDC_MBIRTH_REGION               2220
#define IDC_WCHECK_DATE                 2221
#define IDC_FATHER_DV                   2222
#define IDC_MBIRTH_DISTRICT             2223
#define IDC_SURNAME_RV                  2224
#define IDC_MBIRTH_CITY                 2225
#define IDC_NAME_RV                     2226
#define IDC_WMBIRTH_CITY                2226
#define IDC_MRP_COUNTRY                 2227
#define IDC_FATHER_RV                   2228
#define IDC_MRP_REGION                  2229
#define IDC_CITIZEN_DV                  2230
#define IDC_MRP_DISTRICT                2231
#define IDC_CITIZEN_RV                  2232
#define IDC_MRP_CITY                    2233
#define IDC_MRP_FLAT                    2234
#define IDC_MRP_STREET                  2235
#define IDC_MRP_HOUSE                   2236
#define IDC_MPASSPORT_TYPE              2237
#define IDC_MPASSPORT_SERIA             2238
#define IDC_MPASSPORT_NUMBER            2239
#define IDC_MPASSPORT_DATE              2240
#define IDC_MPASSPORT_BY                2242
#define IDC_MFAMILY_STATUS              2243
#define IDC_GROUND_TYPE                 2244
#define IDC_MACT_NUMBER                 2245
#define IDC_MCHECK_BANK                 2246
#define IDC_MACT_DATE                   2247
#define IDC_MDUTY                       2248
#define IDC_MACT_BY                     2249
#define IDC_MDUTY2                      2250
#define IDC_D8_NUMBER                   2251
#define IDC_WBIRTH_COUNTRY              2252
#define IDC_MMONEY_TYPE                 2253
#define IDC_D8_BABY                     2254
#define IDC_WBIRTH_REGION               2255
#define IDC_MCHECK_NUMBER               2256
#define IDC_D8_TO                       2257
#define IDC_WBIRTH_DISTRICT             2258
#define IDC_WRP_COUNTRY                 2259
#define IDC_D8_WHERE                    2270
#define IDC_WBIRTH_CITY                 2271
#define IDC_WRP_REGION                  2272
#define IDC_WRP_STREET                  2273
#define IDC_WRP_DISTRICT                2274
#define IDC_WRP_HOUSE                   2275
#define IDC_WRP_CITY                    2276
#define IDC_WRP_FLAT                    2277
#define IDC_WPASSPORT_TYPE              2278
#define IDC_WPASSPORT_SERIA             2279
#define IDC_WPASSPORT_NUMBER            2280
#define IDC_WPASSPORT_DATE              2291
#define IDC_WPASSPORT_BY                2292
#define IDC_WDUTY                       2293
#define IDC_WDUTY2                      2294
#define IDC_WFAMILY_STATUS              2295
#define IDC_WMONEY_TYPE                 2296
#define IDC_WACT_NUMBER                 2297
#define IDC_WCHECK_NUMBER               2298
#define IDC_WACT_DATE                   2299
#define IDC_WCHECK_BANK                 2300
#define IDC_WACT_BY                     2301
#define IDC_ACT_LABEL                   2302
#define IDC_PERIOD                      2303
#define IDC_LABEL_FROM                  2304
#define IDC_LABEL_TILL                  2305
#define IDC_MILITARY                    2306
#define IDC_NODATA                      2307
#define IDC_SERIA                       2308
#define IDC_EXTNOTICE                   2309
#define IDC_NOCHILDREN                  2309
#define IDC_DECLARANT_DLG               2310
#define IDC_SINGLECHILD                 2310
#define IDC_LBL_DECLARANT_PSERIA        2311
#define IDC_LBL_DECLARANT_PNUMBER       2312
#define IDC_LBL_DECLARANT_PDATE         2313
#define IDC_LBL_DECLARANT_PBY           2314
#define IDC_TYPE1                       2315
#define IDC_SERIA1                      2316
#define IDC_RAGS1                       2317
#define IDC_DOCTO                       2318
#define IDC_NUMBER1                     2319
#define IDC_DATE1                       2320
#define IDC_BY1                         2321
#define IDC_WHO1                        2322
#define IDC_SERIA2                      2323
#define IDC_WHO2                        2324
#define IDC_EXTNOTICES                  2325
#define IDC_RAGS2                       2326
#define IDC_NUMBER2                     2327
#define IDC_MNACT_LABEL                 2328
#define IDC_NUMBER3                     2329
#define IDC_MNOTICE_LABEL               2329
#define IDC_DATE2                       2330
#define IDC_WNOTICE_LABEL               2330
#define IDC_WNACT_LABEL                 2331
#define IDC_DATE3                       2332
#define IDC_TYPE2                       2333
#define IDC_MDATE_LABEL                 2334
#define IDC_TYPE3                       2335
#define IDC_BY2                         2336
#define IDC_RAGS3                       2337
#define IDC_WDATE_LABEL                 2338
#define IDC_TYPE4                       2339
#define IDC_MBY_LABEL                   2340
#define IDC_NUMBER4                     2341
#define IDC_WBY_LABEL                   2342
#define IDC_DATE4                       2343
#define IDC_MNOTICE                     2344
#define IDC_RAGS4                       2345
#define IDC_WNOTICE                     2346
#define IDC_TYPE5                       2347
#define IDC_MARRIAGE_BY                 2348
#define IDC_NUMBER5                     2349
#define IDC_MCERTIFICATE_SERIA          2350
#define IDC_DATE5                       2351
#define IDC_MCERTIFICATE_NUMBER         2352
#define IDC_RAGS5                       2353
#define IDC_LABEL_DATEREG               2354
#define IDC_TYPE6                       2355
#define IDC_LABEL_NUMBER                2356
#define IDC_NUMBER6                     2357
#define IDC_LABEL_MARRIAGE_BY           2358
#define IDC_DATE6                       2359
#define IDC_LABEL_MARRIAGE_NUMBER       2360
#define IDC_RAGS6                       2361
#define IDC_LABEL_MARRIAGE_DATE         2362
#define IDC_TYPE7                       2363
#define IDC_LABEL_MMARRIAGE_NUMBER      2364
#define IDC_NUMBER7                     2365
#define IDC_LABEL_GROUND                2366
#define IDC_DATE7                       2367
#define IDC_LABEL_MOLD_SURNAME          2368
#define IDC_RAGS7                       2369
#define IDC_LABEL_MNEW_SURNAME          2370
#define IDC_TYPE8                       2371
#define IDC_LABEL_MNAME                 2372
#define IDC_NUMBER8                     2373
#define IDC_LABEL_MPATRONYMIC           2374
#define IDC_DATE8                       2375
#define IDC_LABEL_MBIRTH_DATE           2376
#define IDC_RAGS8                       2377
#define IDC_LABEL_MPASSPORT_SERIA       2378
#define IDC_TYPE9                       2379
#define IDC_LABEL_MPASSPORT_NUMBER      2380
#define IDC_NUMBER9                     2381
#define IDC_LABEL_MPASSPORT_DATE        2382
#define IDC_DATE9                       2383
#define IDC_LABEL_MPASSPORT_BY          2384
#define IDC_RAGS9                       2385
#define IDC_LABEL_MRP_COUNTRY           2386
#define IDC_TYPE10                      2387
#define IDC_LABEL_MRP_REGION            2388
#define IDC_NUMBER10                    2389
#define IDC_LABEL_MRP_DISTRICT          2390
#define IDC_DATE10                      2391
#define IDC_LABEL_MRP_CITY              2392
#define IDC_RAGS10                      2393
#define IDC_LABEL_MRP_HOUSE             2394
#define IDC_WHO3                        2395
#define IDC_LABEL_MRP_FLAT              2396
#define IDC_WHO4                        2397
#define IDC_LABEL_MDUTY                 2398
#define IDC_WHO5                        2399
#define IDC_LABEL_MCHECK_NUMBER         2400
#define IDC_WHO6                        2401
#define IDC_LABEL_MCHECK_DATE           2402
#define IDC_TYPE11                      2403
#define IDC_LABEL_MCHECK_BANK           2404
#define IDC_DATE11                      2404
#define IDC_NUMBER11                    2405
#define IDC_LABEL_MCERTIFICATE_NUMBER   2405
#define IDC_LABEL_MCERTIFICATE_SERIA    2406
#define IDC_RAGS11                      2406
#define IDC_LABEL_WOLD_SURNAME          2407
#define IDC_TYPE12                      2408
#define IDC_LABEL_WNEW_SURNAME          2409
#define IDC_NUMBER12                    2410
#define IDC_LABEL_WNAME                 2411
#define IDC_DATE12                      2412
#define IDC_LABEL_WPATRONYMIC           2413
#define IDC_RAGS12                      2414
#define IDC_LABEL_WBIRTH_DATE           2415
#define IDC_WHO7                        2416
#define IDC_LABEL_WRP_COUNTRY           2417
#define IDC_WHO8                        2418
#define IDC_LABEL_WRP_REGION            2419
#define IDC_WHO9                        2420
#define IDC_LABEL_WRP_DISTRICT          2421
#define IDC_WHO10                       2422
#define IDC_LABEL_WRP_CITY              2423
#define IDC_WHO11                       2424
#define IDC_LABEL_WRP_HOUSE             2425
#define IDC_WHO12                       2426
#define IDC_LABEL_WRP_FLAT              2427
#define IDC_LABEL_WPASSPORT_SERIA       2428
#define IDC_LABEL_WPASSPORT_NUMBER      2429
#define IDC_LABEL_WPASSPORT_DATE        2430
#define IDC_LABEL_WPASSPORT_BY          2431
#define IDC_WCERTIFICATE_SERIA          2432
#define IDC_LABEL_WCERTIFICATE_NUMBER   2433
#define IDC_WCERTIFICATE_NUMBER         2434
#define IDC_LABEL_MRP_STREET            2435
#define IDC_LABEL_WDUTY                 2436
#define IDC_LABEL_WCHECK_NUMBER         2437
#define IDC_LABEL_WCHECK_DATE           2438
#define IDC_LABEL_WCHECK_BANK           2439
#define IDC_LABEL_WCERTIFICATE_SERIA    2440
#define IDC_LABEL_WMARRIAGE_NUMBER      2441
#define IDC_LABEL_DATE                  2442
#define IDC_LABEL_WRP_STREET            2443
#define IDC_LABEL_NKIDS                 2444
#define IDC_MSURNAME_1                  2445
#define IDC_MNAME_1                     2446
#define IDC_MPATRONYMIC_1               2447
#define IDC_WSURNAME_1                  2448
#define IDC_WNAME_1                     2449
#define IDC_WPATRONYMIC_1               2450
#define IDC_SURNAME_TO                  2451
#define IDC_NAME_TO                     2452
#define IDC_PATRONYMIC_TO               2453
#define IDC_TOLABEL                     2454
#define IDC_TORAGS                      2455
#define IDC_VERDICT_OF                  2455
#define IDC_MSURNAME                    2456
#define IDC_WSURNAME                    2457
#define IDC_VERDICT_NUMBER              2457
#define ID_STATIC                       2458
#define IDC_NEWFATHER_SURNAME           2458
#define IDC_NEWDBNAME                   2459
#define IDC_NEWMOTHER_SURNAME           2459
#define IDC_YEAR                        2460
#define IDC_NEWFATHER_NAME              2460
#define IDC_WARINGMESSAGE               2461
#define IDC_NEWFATHER_PATRONYMIC        2461
#define IDC_VERSION                     2462
#define IDC_NEWMOTHER_NAME              2462
#define IDC_CHILD_BP_COUNTRY_CHECK      2463
#define IDC_NEWMOTHER_PATRONYMIC        2463
#define IDC_REGINFO                     2463
#define IDC_CHILD_BP_REGION_CHECK       2464
#define IDC_LICENSED_TO                 2464
#define IDC_RADIO_BIRTHES               2465
#define IDC_CITIZENSHIP_ACT             2465
#define IDC_RADIO_MARRIAGES             2466
#define IDC_CITIZENSHIP_CERTS           2466
#define IDC_RADIO_DIVORCES              2467
#define IDC_CITIZENSHIP_OTHER           2467
#define IDC_RADIO_CHANGES               2468
#define IDC_RADIO_DEATHES               2469
#define IDC_RADIO_ENVELOPES             2470
#define IDC_CHILD_BP_DISTRICT_CHECK     2470
#define IDC_CHILD_BP_CITY_CHECK         2471
#define IDC_FORM_GROUP                  2481
#define IDC_OLD_SURNAME                 2482
#define IDC_OLD_NAME                    2483
#define IDC_OLD_PATRONYMIC              2484
#define IDC_NEW_SURNAME                 2485
#define IDC_NEW_NAME                    2486
#define IDC_NEW_PATRONYMIC              2487
#define IDC_LBL_SURNAME                 2488
#define IDC_LBL_NAME                    2489
#define IDC_LBL_PATRONYMIC              2490
#define IDC_LBL_ALTNAME                 2490
#define IDC_LBL_BEFORE                  2491
#define IDC_LBL_TYPE                    2491
#define IDC_LBL_AFTER                   2492
#define IDC_LBL_PHONE                   2492
#define IDC_LBL_DATE                    2493
#define IDC_LBL_ZIP_CODE                2493
#define IDC_LBL_NUMBER                  2494
#define IDC_LBL_BIRTH_DATE              2495
#define IDC_LBL_BP_COUNTRY              2496
#define IDC_LBL_BP_REGION               2497
#define IDC_LBL_BP_DISTRICT             2498
#define IDC_LBL_BP_CITY                 2499
#define IDC_LBL_RESIDENT                2500
#define IDC_LBL_LIVEPLACE               2500
#define IDC_LBL_RP_COUNTRY              2501
#define IDC_LBL_RP_REGION               2502
#define IDC_LBL_RP_DISTRICT             2503
#define IDC_LBL_RP_CITY                 2504
#define IDC_LBL_RP_STREET               2505
#define IDC_LBL_RP_HOUSE                2506
#define IDC_LBL_RP_FLAT                 2507
#define IDC_LBL_PASSPORT_SERIA          2508
#define IDC_LBL_PASSPORT_NUMBER         2509
#define IDC_LBL_PASSPORT_DATE           2510
#define IDC_LBL_CERTIFICATE_SERIA       2511
#define IDC_LBL_CERTIFICATE_NUMBER      2512
#define IDC_LBL_NOTICE                  2513
#define IDC_LBL_BIRTHACT_DATE           2514
#define IDC_LBL_PASSPORT_BY             2515
#define IDC_LBL_BIRTHACT_NUMBER         2516
#define IDC_CHECK_NUMBER                2517
#define IDC_LBL_CHECK_DATE              2518
#define IDC_CHECK_DATE                  2519
#define IDC_LBL_CHECK_BANK              2520
#define IDC_CHECK_BANK                  2521
#define IDC_GR10                        2522
#define IDC_GRSVID                      2523
#define IDC_D43_TO                      2524
#define IDC_D43_NUMBER                  2525
#define IDC_ADODC1                      2526
#define IDC_D43_ABOUT                   2527
#define IDC_DATAGRID1                   2528
#define IDC_PRINT_CITIZEN               2529
#define IDC_NCOPIES                     2530
#define IDC_PSEUDO                      2531
#define IDC_DEATH_REASON                2532
#define IDC_RENEW                       2533
#define IDC_LBL_RENEW                   2535
#define IDC_LBL_LONGTERM                2536
#define IDC_PASSPORT                    2537
#define IDC_FLAGS                       2538
#define IDC_LBL_DECLARANT               2539
#define IDC_RLIST                       2540
#define IDC_CITIZEN                     2541
#define IDC_UNMARRIED                   2542
#define IDC_LED_RAGS                    2543
#define IDC_LED_REGION                  2544
#define IDC_LED_DISTRICT                2545
#define IDC_LED_CITY                    2546
#define IDC_SECURITY                    2547
#define IDC_EDIT1                       2548
#define IDC_NUMBER_MARRIAGE             2548
#define IDC_OOINFO                      2548
#define IDC_PASSWORD                    2548
#define IDC_USER                        2548
#define IDC_DEFNOTICE                   2548
#define IDC_DECLARANT_20                2549
#define IDC_NUMBER_DIVORCE              2549
#define IDC_MSOINFO                     2549
#define IDC_PASSWORD1                   2549
#define IDC_DEFNOTICE2                  2549
#define IDC_EDIT2                       2549
#define IDC_DUTY                        2550
#define IDC_PASSWORD2                   2550
#define IDC_OLDSURNAME                  2551
#define IDC_POST                        2551
#define IDC_OLDNAME                     2552
#define IDC_NEWNAME                     2553
#define IDC_OLDPATRONYMIC               2554
#define IDC_NEWPATRONYMIC               2555
#define IDC_PRIMPB                      2556
#define IDC_ADDRESS                     2557
#define IDC_OLPRIMPB                    2558
#define IDC_PHONES                      2559
#define IDC_NEWPRIMPB                   2560
#define IDC_FULLDATE1                   2561
#define IDC_FULLDATE2                   2562
#define IDC_TOROVD                      2563
#define IDC_TO_LABEL                    2564
#define IDC_CHECK1                      2565
#define IDC_CHECK2                      2566
#define IDC_TEMPL_LIST                  2567
#define IDC_RADIO1                      2568
#define IDC_RADIO2                      2569
#define IDC_RADIO3                      2570
#define IDC_RADIO4                      2571
#define IDC_RADIO5                      2572
#define IDC_RADIO6                      2573
#define IDC_RADIO7                      2574
#define IDC_RADIO8                      2575
#define IDC_RADIO9                      2576
#define IDC_TEMPLATES_OF                2577
#define IDC_ACTIMAGE                    2578
#define IDC_CURDB                       2579
#define IDC_COMMONLIST                  2580
#define IDC_PASSPORTS                   2581
#define IDC_MILCARS                     2582
#define IDC_PRINTWHAT                   2583
#define IDC_PIB                         2584
#define IDC_SEARCHLIST                  2585
#define IDC_NUMLIST                     2586
#define IDC_STYLE_STANDART              2587
#define IDC_STYLE_SILVER                2588
#define IDC_STYLE_SUMMER                2589
#define IDC_STYLE_REVOLUTION            2590
#define IDC_STYLE_TRANQUIL              2591
#define IDC_STYLE_ALPINE                2592
#define IDC_RADIO_STANDART              2593
#define IDC_RADIO_SILVER                2594
#define IDC_RADIO_SUMMER                2595
#define IDC_RADIO_REVOLUTION            2596
#define IDC_RADIO_TRANQUIL              2597
#define IDC_RADIO_ALPINE                2598
#define IDC_CLRPICKER_LEFT              2599
#define IDC_CLRPICKER_RIGHT             2600
#define IDC_CHECK_USEGRADIENT           2601
#define IDC_STYLE_USER                  2602
#define IDC_LBL_PIB                     2603
#define IDC_LBL_NAZ                     2604
#define IDC_FRAME1                      2605
#define IDC_FRAME2                      2606
#define IDC_FRAME3                      2607
#define IDC_FRAME4                      2608
#define IDC_FRAME5                      2609
#define IDC_FRAME6                      2610
#define IDC_FRAME7                      2611
#define IDC_YEAR_SPIN                   2612
#define IDC_LBL_MILITARY                2613
#define IDC_VERDICT_DATE                2614
#define IDC_NEWBIRTH_DATE               2615
#define IDC_STATIC_FRAME                2616
#define IDC_FRAME                       2617
#define IDC_AS_DATEREG                  2618
#define IDC_LBL_CASE                    2619
#define IDC_LBL_ADDRESS                 2620
#define IDC_LBL_PHONES                  2621
#define IDC_RTREE                       2622
#define IDC_RADIO_TREE                  2623
#define IDC_RADIO_LIST                  2624
#define IDC_LBL_OR                      2625
#define IDC_WARNING                     2626
#define IDC_CHILD_OF                    2627
#define IDC_BTN_UP                      2628
#define IDC_GEOLIST                     2629
#define IDC_PROGRESS                    2630
#define IDC_WHAT                        2631
#define IDC_SENDER                      2632
#define IDC_SENDER_COUNTRY              2633
#define IDC_SENDER_REGION               2634
#define IDC_SENDER_CITY                 2635
#define IDC_SENDER_ADDRESS              2636
#define IDC_SENDER_INDEX                2637
#define IDC_WHAT_TODO                   2638
#define IDC_MESSAGE                     2639
#define IDC_ATTICON                     2640
#define IDC_TABLE_NAME                  2641
#define IDC_ADDRESSEE                   2642
#define IDC_ADDRESSEE_COUNTRY           2643
#define IDC_ALIVE_FLAG_EDIT             2644
#define IDC_ADDRESSEE_REGION            2645
#define IDC_INFO                        2646
#define IDC_ADDRESSEE_CITY              2647
#define IDC_ATTENTION_ICON              2648
#define IDC_ADDRESSEE_ADDRESS           2649
#define IDC_BIRTH_ICON                  2650
#define IDC_ADDRESSEE_INDEX             2651
#define IDC_TITLE                       2652
#define IDC_EMAIL                       2653
#define IDC_ONE_PAGE                    2654
#define IDC_TWO_PAGE                    2655
#define IDC_ONE_PAGE_B                  2656
#define IDC_LINE1                       2656
#define IDC_CHECK_MARRIAGES             2657
#define IDC_CHECK_DIVORCES              2658
#define IDC_CHECK_CHANGES               2659
#define IDC_FILENAME                    2660
#define IDC_SORT_PIB                    2661
#define IDC_SORT_PIB_AFTER              2662
#define IDC_SORT_PIB_BEFORE             2663
#define IDC_SORT_BIRTH_DATE             2664
#define IDC_SORT_LIVE_PLACE             2665
#define IDC_ONE_SHEET                   2666
#define IDC_MANY_SHEETS                 2667
#define IDC_REGCODE                     2668
#define IDC_REG_LATER                   2669
#define IDC_COPYRIGHT                   2670
#define IDC_WARNING_ICON                2671
#define IDC_KEY1                        2672
#define IDC_KEY2                        2673
#define IDC_KEY3                        2674
#define IDC_KEY4                        2675
#define IDC_KEY5                        2676
#define IDC_KEY6                        2677
#define IDC_ZIPLIST                     2678
#define IDC_NEVER                       2679
#define IDC_MONDAY                      2680
#define IDC_TUESDAY                     2681
#define IDC_WEDNESDAY                   2682
#define IDC_THURSDAY                    2683
#define IDC_FRIDAY                      2684
#define IDC_SATURDAY                    2685
#define IDC_EVERYDAY                    2686
#define IDC_DONT_FILTER                 2687
#define IDC_FILTER_YES                  2688
#define IDC_FILTER_NO                   2689
#define IDC_COMBO1                      2690
#define IDC_FILELIST                    2691
#define IDC_TOSOCPROT                   2692
#define IDC_MPIB                        2693
#define IDC_PARENTPIBS                  2694
#define IDC_FATHERPIB                   2695
#define IDC_CHILDPIB                    2696
#define IDC_NAMELIST                    2697
#define IDC_MOTHERPIB                   2698
#define IDC_LABEL                       2699
#define IDC_NOPRINT_UNKNOWNS            2700
#define IDC_TWO_SURNAMES                2701
#define IDC_MAKE_DBF                    2701
#define IDC_SINGLE_SURNAME              2702
#define IDC_EACH_TO_EACH                2703
#define IDC_ALL_TO_ONE                  2704
#define IDC_LBL_PATH                    2705
#define IDC_STATIC_FONT_SAMPLE          2706
#define IDC_FONT                        2707
#define IDC_CHECK_BIRTH                 2708
#define IDC_CHECK_MARRIAGE              2709
#define IDC_TVK_EMPTY                   2710
#define IDC_CHECK_DEATH                 2711
#define IDC_MAKE_XLS                    2712
#define IDC_TAB                         2713
#define IDC_SCRIPT_COMBO                2714
#define IDC_LBL_VBSCRIPT                2715
#define IDC_DATEREG_MARRIAGE            2716
#define IDC_RMARRIAGE_COMBO             2717
#define IDC_RMARRIAGE_EDIT              2718
#define IDC_MSOFFICE                    2718
#define IDC_DATEREG_DIVORCE             2719
#define IDC_OPENOFFICE                  2719
#define IDC_RDIVORCE_COMBO              2720
#define IDC_LOGIN                       2720
#define IDC_RDIVORCE_EDIT               2721
#define IDC_SHOW_PASSWORD               2721
#define IDC_USERS                       2722
#define IDC_ADDNEW                      2723
#define IDC_DELETE                      2724
#define IDC_ACT                         2726
#define IDC_LBL_START                   2727
#define IDC_LBL_TERMIN                  2728
#define IDC_START_DATE                  2729
#define IDC_EMAILLINK                   2730
#define IDC_WEBSITE                     2731
#define IDC_UNDERLINE                   2731
#define IDC_PRINTSINGLE                 2732
#define IDC_CITYTYPE                    2733
#define IDC_SENDER_LABEL                2734
#define IDC_ADDRESSEE_LABEL             2735
#define IDC_SENDER_COUNTRY_LABEL        2736
#define IDC_ADDRESSEE_COUNTRY_LABEL     2737
#define IDC_SENDER_CITY_LABEL           2738
#define IDC_ADDRESSEE_CITY_LABEL        2739
#define IDC_SENDER_ADDRESS_LABEL        2740
#define IDC_ADDRESSEE_ADDRESS_LABEL     2741
#define IDC_SENDER_INDEX_LABEL          2742
#define IDC_ADDRESSEE_INDEX_LABEL       2743
#define ID_TREEFILECTRL_UP              32501
#define ID_TREEFILECTRL_UPONELEVEL      32502
#define ID_TREEFILECTRL_REFRESH         32503
#define ID_TREEFILECTRL_BACK            32504
#define ID_TREEFILECTRL_FORWARD         32505
#define ID_TREEFILECTRL_OPEN            32506
#define ID_TREEFILECTRL_DELETE          32507
#define ID_TREEFILECTRL_RENAME          32508
#define ID_TREEFILECTRL_PROPERTIES      32509
#define ID_SEARCH_LIST                  32768
#define ID_CMB_SCALE                    32770
#define ID_TOGGLE_INSERT                32771
#define ID_FINDPATH                     32772
#define ID_BIRTH                        32773
#define ID_FATHER                       32774
#define ID_MARRIAGE                     32775
#define ID_DIVORCE                      32776
#define ID_CHANGE                       32777
#define ID_DEATH                        32778
#define ID_FIND_EQU                     32779
#define ID_PARTIAL_MATCHING             32780
#define ID_SETTINGS                     32781
#define ID_RECORD_NEW                   32782
#define ID_REGPLACE                     32783
#define ID_PASSPORT                     32784
#define ID_RECORD_DELETE                32785
#define ID_NODEADPASSPORT               32786
#define ID_NATIONAL                     32787
#define ID_CERTIFICATE                  32788
#define ID_CITIZENSHIP                  32789
#define ID_WINDOW                       32790
#define ID_GEOGRAPHY                    32791
#define IDD_ADDCOUNTRY                  32792
#define ID_PMMD                         32793
#define ID_PMMD2                        32794
#define IDD_ADDREGION                   32795
#define ID_NPM                          32796
#define IDD_ADDDISTRICT                 32797
#define ID_FNATIONAL                    32798
#define IDD_ADDCITY                     32799
#define ID_FCITIZENSHIP                 32800
#define IDD_DELETE                      32801
#define ID_MNATIONAL                    32802
#define ID_REGISTRARS                   32803
#define ID_MCITIZENSHIP                 32804
#define ID_EXTNOTES                     32805
#define ID_FPASSPORT                    32806
#define ID_MPASSPORT                    32807
#define ID_CHILDSHURNAME                32808
#define ID_CMB_SURNAME                  32809
#define ID_NATIANALITY                  32810
#define ID_SURNAME                      32811
#define ID_CMB_NUMBER                   32812
#define ID_FIND                         32813
#define ID_PRINT                        32814
#define ID_RETURN                       32816
#define ID_PAGE_SETUP                   32817
#define ID_MAGNIFIER                    32818
#define ID_EDIT                         32819
#define ID_MEDICS                       32827
#define ID_MILITARY                     32830
#define ID_NOMILITARYDOC                32831
#define ID_MOTHERIS                     32832
#define ID_DECPASSPORT                  32833
#define ID_PMMD1                        32834
#define ID_FOUNDLING                    32835
#define ID_FATHER_BY_MOTHER             32836
#define ID_FATHER_BY_DECLARANT          32837
#define ID_OTHER_MARRIAGE               32838
#define ID_NOBIRTH_DATE                 32841
#define ID_NODEATH_DATE                 32842
#define ID_POLICE                       32843
#define ID_LST_SURNAME                  32844
#define ID_GRIDLINES                    32848
#define ID_NAMES                        32854
#define ID_PATRONYMICS                  32855
#define ID_STREETS                      32856
#define ID_DEATHCAUSES                  32857
#define ID_CITIZENSHIPS                 32858
#define ID_BANK                         32859
#define ID_ABC                          32860
#define ID_BAR_UP                       32861
#define ID_BAR_DOWN                     32862
#define ID_BIRTHPLACE                   32863
#define ID_BAR_LEFT                     32863
#define ID_BAR_RIGHT                    32864
#define ID_ADO                          32866
#define IDS_DELETE_CASE                 32867
#define IDS_DELETE_QUESTION             32868
#define IDS_RM01                        32869
#define IDS_RM02                        32870
#define IDS_RM03                        32871
#define IDS_RM04                        32872
#define IDS_RM05                        32873
#define IDS_RM06                        32874
#define IDS_RM07                        32875
#define IDS_RM08                        32876
#define IDS_RM09                        32877
#define IDS_RM10                        32878
#define IDS_RM11                        32879
#define IDS_RM12                        32880
#define IDS_AUTHOR                      32881
#define IDS_VLADIMIR                    32882
#define IDS_KOLTSOV                     32883
#define IDS_SOFTWARE                    32884
#define IDS_UM01                        32885
#define IDS_UM02                        32886
#define IDS_UM03                        32887
#define IDS_UM04                        32888
#define IDS_UM05                        32889
#define IDS_UM06                        32890
#define IDS_UM07                        32891
#define IDS_UM08                        32892
#define IDS_UM09                        32893
#define IDS_UM10                        32894
#define IDS_UM11                        32895
#define IDS_UM12                        32896
#define IDS_M01                         32897
#define IDS_M02                         32898
#define IDS_M03                         32899
#define IDS_M04                         32900
#define IDS_M05                         32901
#define IDS_M06                         32902
#define IDS_M07                         32903
#define IDS_M08                         32904
#define IDS_M09                         32905
#define IDS_M10                         32906
#define IDS_M11                         32907
#define IDS_M12                         32908
#define IDS_DEATH_IN                    32909
#define IDS_DEATH_OUT                   32910
#define IDS_BIRTH_IN                    32911
#define IDS_BIRTH_OUT                   32912
#define IDS_DIVORCE_IN                  32913
#define IDS_DIVORCE_OUT                 32914
#define IDS_MARRIAGE_IN                 32915
#define IDS_MARRIAGE_OUT                32916
#define IDS_CHANGE_IN                   32917
#define IDS_CHANGE_OUT                  32918
#define IDS_NOCERT                      32919
#define IDS_FMCITIZENSHIP               32923
#define IDS_FCITIZENSHIP                32924
#define IDS_MCITIZENSHIP                32925
#define IDS_CITIZENSHIP                 32926
#define IDS_NODEADPASSPORT              32927
#define IDP_OLE_INIT_FAILED             32928
#define IDS_DECPASSPORT                 32929
#define IDC_LBL_ABOUT                   32932
#define ID_CHANGESTO                    32934
#define ID_HELPER                       32938
#define ID_WHAT_IS_IT                   32939
#define ID_RECORD_EDIT                  32940
#define ID_SECOND                       32941
#define ID_RENEW                        32942
#define ID_LONGTERM                     32943
#define ID_ENABLE_BIRTHES               32945
#define ID_ENABLE_FATHERS               32946
#define ID_ENABLE_MARRIAGES             32947
#define ID_ENABLE_DIVORCES              32948
#define ID_ENABLE_CHANGES               32949
#define ID_ENABLE_DEATHES               32950
#define ID_DECLDATA20                   32951
#define ID_GOTO_FOUNDREC                32952
#define ID_WORD                         32953
#define ID_CANCEL_EDIT_CNTR             32960
#define ID_NEW_SEARCH                   32961
#define ID_TEMPLATES                    32962
#define ID_FINDIN                       32963
#define ID_CLOSE                        32965
#define ID_FILE_RECENT                  32966
#define ID_MSURNAME                     32967
#define ID_WSURNAME                     32968
#define ID_MNAME                        32969
#define IDD_RENAME                      32970
#define ID_FOLDER_TREE                  32971
#define ID_SETMILITARYDOC               32972
#define ID_ZOOM_IN                      32978
#define ID_ZOOM_OUT                     32979
#define IDD_SETTYPE_COUNTRY             32982
#define IDD_SETTYPE_REGION              32983
#define IDD_SETTYPE_TERRITORY           32984
#define IDD_SETTYPE_DISTRICT            32985
#define IDD_SETTYPE_CITY                32986
#define IDD_SETTYPE_SMT                 32987
#define IDD_SETTYPE_HAMLET              32988
#define IDD_SETTYPE_VILLAGE             32989
#define IDD_SET_OWNER                   32990
#define IDD_ADD_RAGS                    32991
#define IDD_DELETE_RAGS                 32992
#define IDC_STILL_BORN                  32993
#define ID_HELP_UKR                     32994
#define ID_HELP_RUS                     32995
#define ID_TOOLBARS                     32996
#define IDD_SETTYPE_MAINCITY            32997
#define ID_UNZIP                        32998
#define ID_ZIPDB                        32999
#define ID_NOBIRTH_PLACE                33001
#define ID_NOLIVE_PLACE                 33002
#define ID_NOCERTIFICATE                33003
#define ID_REGISTRATION                 33005
#define ID_IMPORT                       33006
#define ID_HELP_CONTENT                 33007
#define IDD_ADD_TO_USEMAP               33008
#define ID_WNAME                        33009
#define ID_EXCEL                        33012
#define ID_ADD_TO_PARENT                33013
#define ID_ADD_TO_CURRENT               33014
#define ID_ADD_TO_LIST                  33015
#define ID_LAWS                         33016
#define ID_GO_BACK                      33017
#define ID_BUTTON33018                  33018
#define ID_GO_FORWARD                   33018
#define ID_GO_HOME                      33020
#define ID_PRINT_PAGE                   33022
#define ID_REFRESH                      33023
#define ID_FONT                         33024
#define ID_MENUITEM33028                33028
#define IDD_DELETE_ITEM                 33029
#define ID_DEADSURNAME                  33030
#define ID_DEADNAME                     33031
#define ID_DEADPATRONYMIC               33032
#define ID_SURNAMES                     33033
#define ID_FATHERPLACE                  33034
#define ID_MOTHERPLACE                  33035
#define IDS_FSTATUS_IN                  33036
#define IDS_FSTATUS_OUT                 33037
#define IDS_ENVELOPE                    33038
#define IDS_ELECTION_LIST               33039
#define IDS_PATH_NAME_EXT               33040
#define ID_NAME                         33041
#define ID_PATRONYMIC                   33042
#define ID_NOMEDICSM                    33043
#define ID_NOMEDICSW                    33044
#define ID_NOMEDIC                      33045
#define ID_YESMEDICS                    33046
#define ID_SAVE_FILE_AS_UKR             61441

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        502
#define _APS_NEXT_COMMAND_VALUE         33047
#define _APS_NEXT_CONTROL_VALUE         2746
#define _APS_NEXT_SYMED_VALUE           114
#endif
#endif
