//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by EraABC.rc
//
#define IDD_ABOUTBOX                    100
#define ID_BIRTH                        101
#define ID_FATHER                       102
#define IDP_FAILED_OPEN_DATABASE        103
#define ID_MARRIAGE                     103
#define IDP_SOCKETS_INIT_FAILED         104
#define ID_DIVORCE                      104
#define ID_CHANGE                       105
#define ID_DEATH                        106
#define IDR_TREEFILECTRL_POPUP          114
#define IDR_MAINFRAME                   128
#define IDR_ERAABCTYPE                  129
#define IDC_FOLDER_TREE                 129
#define IDR_ERAGSTYPE                   130
#define IDS_PANE_LABEL                  130
#define IDS_PANE_MESSAGECOMBO           131
#define IDS_PANE_ICON                   132
#define IDR_TREEFILECTRL_NO_DROPMOVE    132
#define IDIL_TABS                       132
#define IDR_TREEFILECTRL_NO_DROPCOPY    133
#define IDR_TREEFILECTRL_DROPCOPY       134
#define IDB_CALENDAR                    134
#define IDI_FILE_NEW                    136
#define IDI_FILE_NEW_GRAY               137
#define IDB_STILLBORN_BOY               137
#define IDI_FILE_OPEN                   138
#define IDR_FILEDROPDOWN                138
#define IDB_STILLBORN_GIRL              138
#define IDI_FILE_OPEN_GRAY              139
#define IDD_SETDEFVAL                   139
#define IDTB_TOOLBARS                   143
#define IDI_BIRTH                       144
#define IDIL_MESSAGES                   144
#define IDI_BIRTH_GRAY                  145
#define IDI_MARRIAGE                    146
#define IDI_MARRIAGE_GRAY               147
#define IDI_DIVORCE                     148
#define IDI_DIVORCE_GRAY                149
#define IDI_DEATH                       150
#define IDI_DEATH_GRAY                  151
#define IDI_CHANGE                      152
#define IDI_CHANGE_GRAY                 153
#define IDD_FORM_BIRTH                  154
#define IDI_ATTENTION                   154
#define IDD_FORM_MARRIAGE               155
#define IDB_BOY                         157
#define IDD_FORM_DIVORCE                158
#define IDD_FORM_DEATH                  159
#define IDD_FORM_CHANGE                 160
#define IDB_GIRL                        162
#define IDB_YES256                      168
#define IDB_YES256ACTIVED               169
#define IDB_NO256                       170
#define IDB_NO256ACTIVED                171
#define IDB_DEATH                       172
#define IDIL_HEADER                     175
#define IDI_CLOSE_APP                   208
#define IDI_INFO                        209
#define IDB_MAN256                      253
#define IDB_WOMAN256                    254
#define IDB_FIANCE256                   257
#define IDB_FIANCEE256                  258
#define IDB_FILE_OPEN                   274
#define IDB_FILE_OPEN_OUT               276
#define IDTB_MAIN_TOOLBAR               277
#define IDB_BTN_BIRTH                   280
#define IDB_BTN_BIRTH_OUT               281
#define IDB_BTN_MARRIAGE                282
#define IDB_BTN_MARRIAGE_OUT            283
#define IDB_BTN_DIVORCE                 284
#define IDB_BTN_DIVORCE_OUT             286
#define IDB_BTN_DEATH_OUT               289
#define IDB_BTN_DEATH                   291
#define IDB_BTN_CHANGE                  292
#define IDB_BTN_CHANGE_OUT              293
#define IDB_BTN_FIRST                   309
#define IDB_BTN_FIRST_OUT               310
#define IDB_BTN_PREV                    311
#define IDB_BTN_PREV_OUT                313
#define IDB_BTN_NEXT                    314
#define IDB_BTN_NEXT_OUT                315
#define IDB_BTN_LAST                    316
#define IDB_BTN_LAST_OUT                317
#define IDB_BTN_RECORD_NEW              318
#define IDB_BTN_RECORD_NEW_OUT          319
#define IDB_BTN_RECORD_DELETE           320
#define IDB_BTN_RECORD_DELETE_OUT       321
#define IDB_BTN_HELP                    329
#define IDB_BTN_HELP_OUT                330
#define IDB_BTN_RECENT                  331
#define IDR_NEWMENU256                  337
#define IDB_BTN_FILE_NEW                338
#define IDIL_ABCSEX                     346
#define IDB_HDRUP                       349
#define IDB_HDRDOWN                     350
#define IDB_BTN_FOLDER_TREE             357
#define IDI_FOLDERTREE                  358
#define IDD_FILE_NEW                    366
#define IDI_YES                         384
#define IDI_NO                          385
#define IDC_ERABC_VERSION               1000
#define IDC_DATEREG                     1003
#define IDC_CHILDFACE                   1004
#define IDC_NUMBER                      1006
#define IDC_SEX                         1007
#define IDC_DONTSHOW                    1007
#define IDC_MSGTEXT                     1008
#define IDC_SURNAME                     1013
#define IDC_NAME                        1026
#define IDC_MNEW_SURNAME                1027
#define IDC_PATRONYMIC                  1028
#define IDC_WNEW_SURNAME                1029
#define IDD_YESNO                       1101
#define IDC_YNMESSAGE                   1190
#define IDC_YNQUESTION                  1192
#define IDC_MOLD_SURNAME                1205
#define IDC_WOLD_SURNAME                1207
#define IDC_MNAME                       1209
#define IDC_MPATRONYMIC                 1210
#define IDC_WNAME                       1211
#define IDC_WPATRONYMIC                 1212
#define IDC_OLD_SURNAME                 1482
#define IDC_OLD_NAME                    1483
#define IDC_OLD_PATRONYMIC              1484
#define IDC_NEW_SURNAME                 1485
#define IDC_NEW_NAME                    1486
#define IDC_NEW_PATRONYMIC              1487
#define IDC_ALIVE_FLAG                  2032
#define IDC_YEAR                        2460
#define IDC_YEAR_SPIN                   2627
#define ID_TREEFILECTRL_UP              32771
#define ID_RECORD_NEW                   32772
#define ID_RECORD_DELETE                32773
#define ID_BUTTON32773                  32773
#define ID_TOOLS_SHOWFILES              32774
#define ID_HELP_UKR                     32774
#define ID_AFFILIATION                  32775
#define ID_HELP_RUS                     32775
#define ID_TOOLS_ALLOWRENAME            32776
#define ID_TOGGLE_INSERT                32776
#define ID_TOOLS_ALLOWOPEN              32777
#define ID_TREEFILECTRL_UPONELEVEL      32778
#define ID_TOOLS_ALLOWSPROPERTIES       32779
#define ID_TOOLS_ALLOWDELETE            32780
#define ID_TOOLS_ALLOWDRAGDROP          32781
#define ID_TREEFILECTRL_OPEN            32782
#define ID_TREEFILECTRL_DELETE          32783
#define ID_TREEFILECTRL_RENAME          32784
#define ID_TREEFILECTRL_PROPERTIES      32785
#define ID_TOOLS_HIDEREMOVABLE          32786
#define ID_TOOLS_HIDEFIXED              32787
#define ID_TOOLS_HIDECDROM              32788
#define ID_TOOLS_HIDERAMDISKS           32789
#define ID_TREEFILECTRL_REFRESH         32790
#define ID_TOOLS_HIDEREMOTE             32791
#define ID_TOOLS_FILENAMEMASK           32792
#define ID_TOOLS_HIDEARCHIVE            32793
#define ID_TOOLS_HIDECOMPRESSED         32794
#define ID_TOOLS_HIDEHIDDEN             32795
#define ID_TOOLS_HIDEREADONLY           32796
#define ID_TOOLS_HIDESYSTEM             32797
#define ID_TOOLS_HIDETEMPORARY          32798
#define ID_TOOLS_HIDEENCRYPTED          32799
#define ID_TOOLS_HIDEOFFLINE            32800
#define ID_TOOLS_HIDEREPARSEPOINT       32801
#define ID_TOOLS_HIDESPARSE             32802
#define ID_TREEFILECTRL_BACK            32803
#define ID_TREEFILECTRL_FORWARD         32804
#define ID_TOOLS_AUTOREFRESH            32811
#define ID_TOOLS_SETROOTFOLDER          32812
#define ID_TOOLS_HIDENETWORK            32813
#define ID_TOOLS_SHOWSHAREDFOLDERS      32814
#define ID_TOOLS_SHOWALLNETWORKITEMS    32815
#define ID_TOOLS_SHOWNETWORKPRINTERS    32816
#define ID_TOOLS_SHOWNETWORKSHARES      32817
#define ID_TOOLS_SHOWDRIVELABELS        32818
#define ID_TOOLS_HIDEMYCOMPUTER         32819
#define ID_TOOLS_SHOWROOTEDFOLDER       32820
#define ID_TOOLS_SETSELECTEDPATH        32821
#define IDS_KOLTSOV                     32878
#define IDS_SOFTWARE                    32879
#define IDS_UM01                        32880
#define IDS_UM02                        32881
#define IDS_UM03                        32882
#define IDS_UM04                        32883
#define IDS_UM05                        32884
#define IDS_UM06                        32885
#define IDS_UM07                        32886
#define IDS_UM08                        32887
#define IDS_UM09                        32888
#define IDS_UM10                        32889
#define IDS_UM11                        32890
#define IDS_UM12                        32891
#define IDS_M01                         32892
#define IDS_M02                         32893
#define IDS_M03                         32894
#define IDS_M04                         32895
#define IDS_M05                         32896
#define IDS_M06                         32897
#define IDS_M07                         32898
#define IDS_M08                         32899
#define IDS_M09                         32900
#define IDS_M10                         32901
#define IDS_M11                         32902
#define IDS_M12                         32903
#define ID_FOLDER_TREE                  32937
#define ID_HELPER                       32938
#define ID_WHAT_IS_IT                   32939
#define ID_FILE_RECENT                  32966

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        149
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1010
#define _APS_NEXT_SYMED_VALUE           133
#endif
#endif
