//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by EraWiz.rc
//
#define IDI_WIZARD                      130
#define IDD_WIZARD                      131
#define IDB_WIZARD                      134
#define IDW_SETREGION                   136
#define IDI_BIRTH                       144
#define IDI_MARRIAGE                    146
#define IDI_DIVORCE                     148
#define IDI_DEATH                       150
#define IDI_CHANGE                      152
#define IDIL_GEOTREE                    190
#define IDB_BTN_RED_CROSS               300
#define IDIL_RFOLDERS                   387
#define IDD_DBLOAD                      391
#define IDC_SHEETRECT                   1010
#define ST_CAPTION                      1018
#define IDC_REGLIST                     2000
#define IDW_SETRAGS                     2002
#define IDC_RTREE                       2003
#define IDB_UKRAINE                     2003
#define IDC_HAND                        2004
#define IDC_SHORTNAME                   2004
#define IDC_HTREE                       2005
#define IDC_FULLNAME                    2006
#define IDC_MAP                         2007
#define IDI_LEFT_UP                     2008
#define IDC_REGION                      2008
#define IDI_LEFT_DOWN                   2009
#define IDC_DISTRICT                    2009
#define IDC_CITY                        2010
#define IDC_CITYTYPE                    2011
#define IDI_RIGHT_DOWN                  2012
#define IDC_REGION2                     2012
#define IDI_RIGHT                       2013
#define IDC_DISTRICT2                   2013
#define IDC_CITY2                       2014
#define IDW_SETBIRTH                    2014
#define IDC_CITYTYPE2                   2015
#define IDC_PARENT                      2016
#define IDC_COUNTRY2                    2016
#define IDC_CHILD_BP_COUNTRY_CHECK      2017
#define IDC_BYUMVS                      2018
#define IDC_CHILD_BP_REGION_CHECK       2018
#define IDC_TOUMVS                      2019
#define IDW_SETGEOPLACE                 2019
#define IDC_CHILD_BP_DISTRICT_CHECK     2019
#define IDC_BYMIL                       2020
#define IDB_BIRTH                       2020
#define IDC_CHILD_BP_CITY_CHECK         2020
#define IDC_TOMIL                       2021
#define IDC_TITLE1                      2021
#define IDC_BYCOURT                     2022
#define IDC_SERIA_BIRTH                 2022
#define IDW_DIVORCE                     2022
#define IDC_TOTAX                       2023
#define IDC_TITLE2                      2023
#define IDW_SETMEDICS                   2023
#define IDC_SERIA_MARRIAGE              2024
#define IDC_BOSS                        2024
#define IDC_NOCHILDREN                  2025
#define IDB_UKRAINE_256                 2025
#define IDC_SINGLECHILD                 2026
#define IDC_TITLE3                      2027
#define IDB_Zhytomyrska_Oblast          2027
#define IDC_SERIA_DEATH                 2028
#define IDB_Cherkaska_Oblast            2028
#define IDC_SERIA_DIVORCE               2029
#define IDB_Chernihivska_Oblast         2029
#define IDC_SERIA_CHANGE                2030
#define IDB_Crimea                      2030
#define IDC_HOSPITAL1                   2031
#define IDB_Dnipropetrovska_Oblast      2031
#define IDC_HOSPITAL2                   2032
#define IDB_Donetska_Oblast             2032
#define IDC_HOSPITAL3                   2033
#define IDB_Frankivska_Oblast           2033
#define IDC_HOSPITAL4                   2034
#define IDB_Kharkivska_Oblast           2034
#define IDC_HOSPITAL5                   2035
#define IDB_Khmelnytska_Oblast          2035
#define IDC_HOSPITAL6                   2036
#define IDB_Kiev                        2036
#define IDC_HOSPITAL7                   2037
#define IDB_Kirovohradska_Oblast        2037
#define IDC_HOSPITAL8                   2038
#define IDC_HOSPITAL9                   2039
#define IDB_Zaporizhzhska_Oblast        2039
#define IDC_HOSPITAL10                  2040
#define IDB_Zakarpakska_Oblast          2040
#define IDC_HOSPITAL11                  2041
#define IDB_Khersonska_Oblast           2043
#define IDB_Mykolaivska_Oblast          2044
#define IDB_Lvivska_Oblast              2045
#define IDB_Luhanska_Oblast             2046
#define IDB_Volynska_Oblast             2047
#define IDB_Poltavska_Oblast            2048
#define IDB_Rivnenska_Oblast            2049
#define IDB_Odeska_Oblast               2050
#define IDC_PSEUDO1                     2051
#define IDB_Sevastopol                  2051
#define IDC_PSEUDO2                     2052
#define IDB_Sumska_Oblast               2052
#define IDC_PSEUDO3                     2053
#define IDB_Ternopilska_Oblast          2053
#define IDC_PSEUDO4                     2054
#define IDB_Vinnytska_Oblast            2054
#define IDC_PSEUDO5                     2055
#define IDC_PSEUDO6                     2056
#define IDB_Kyivska_Oblast              2056
#define IDC_PSEUDO7                     2057
#define IDB_Cherkasy                    2057
#define IDC_PSEUDO8                     2058
#define IDB_Chernihiv                   2058
#define IDC_PSEUDO9                     2059
#define IDB_Chernovtsy                  2059
#define IDC_PSEUDO10                    2060
#define IDB_Dnipropetrovsk              2060
#define IDC_PSEUDO11                    2061
#define IDB_Kharkiv                     2061
#define IDC_EMBLEM                      2062
#define IDB_Donetsk                     2062
#define IDB_Frankivsk                   2063
#define IDC_VYCONCOM                    2063
#define IDB_Khmelnitsky                 2064
#define IDC_ORGAN                       2064
#define IDB_Kherson                     2066
#define IDB_Chernivtska_Oblast          2067
#define IDB_Zaporizha                   2068
#define IDB_Zhytomyr                    2069
#define IDB_Kirovohrad                  2070
#define IDB_Simferopol                  2071
#define IDB_Mykolaiv                    2072
#define IDB_Lviv                        2073
#define IDB_Luhansk                     2074
#define IDB_Lutsk                       2075
#define IDB_Poltava                     2076
#define IDB_Rivne                       2077
#define IDB_Odessa                      2078
#define IDB_Sumy                        2079
#define IDB_Ternopil                    2080
#define IDB_Vinnytsia                   2081
#define IDB_Uzhgorod                    2082
#define IDIL_RFOLDERS_TC                2083
#define IDC_PROGRESS                    2669
#define IDC_WHAT                        2670

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        2084
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         2064
#define _APS_NEXT_SYMED_VALUE           2000
#endif
#endif
